name: Build and Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run build
      - name: Deploy
        run: echo "Deploy"
  
